# Site settings
title: Natasha's Plog (Programming Blog)
email: natasha.wu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a blog where I (Natasha Wu) will share my incredible
  insights on learning programming and dazzle my readers with
  clever prose and powerful narrative.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://natashawu.github.io" # the base hostname & protocol for your site
twitter_username: natashaswu
github_username:  natashawu

# Build settings
markdown: redcarpet
sass:
  style: :compressed

safe: true
lsi: false