# Site settings
title: Natasha Wu
email: natasha.s.wu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A designer who codes and writes about life
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://natashawu.github.io" # the base hostname & protocol for your site
twitter_username: natashaswu
github_username:  natashawu
instagram_username: natashaswu

# Build settings
# markdown: redcarpet
kramdown:
  input: GFM
sass:
  style: :compressed

safe: true
lsi: false

# Gems
# gems:
#   - jemoji
